### ISSUE TITLE
how to change tooltip background color and font color 

### ISSUE THREAD

**Issue by WXLWEB** [krispo/angular-nvd3#228]

**Comment by krispo** [comment]
You can change tooltip styles directly in your css file:
```css
.nvtooltip.xy-tooltip {
    background-color: lightblue;
    color: darkred;
}
```
