### ISSUE TITLE
How to change font-family for axis, labels and tooltips

### ISSUE THREAD

**Issue by chirag-20** [krispo/angular-nvd3#441]
I couldn't find a way to change font-family of text's used in NVD3 charts.

Can you point me to some documentation or link, which will help me with this.

I tried changing the font-family from css:{} inside chart:{} object, and it didn't work for me.

Please help.

**Comment by krispo** [comment]
Change css styles directly with `!important`:
```css
.nvd3 text {
  font: normal 12px sans-serif !important;
}
.nvd3 .title {
  font: normal 12px sans-serif !important;
}
.nvtooltip {
  font-family: sans-serif !important;
}
...
```
