### ISSUE TITLE
How to bold x axis line in multibar charts?

### ISSUE THREAD

**Issue by rameshvisolve** [krispo/angular-nvd3#625]

**Comment by Darbiol** [comment]
what x axis line are you referring to? these axis lines can be adjusted through css.

example : 

```css
.nvd3.nv-lineChart .nv-y .nv-axis .tick.zero line {
    stroke-opacity : 1;
}
```
